---
abstract: 'WWW::Shorten::SCK - Perl interface to sck.to'
author:
  - 'celogeek <me@celogeek.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::More: 0.94
  WWW::Shorten: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300017, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Shorten-SCK
requires:
  Carp: 0
  Exporter: 0
  WWW::Shorten::generic: 0
  base: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  repository: https://github.com/celogeek/WWW-Shorten-SCK.git
version: 0.002
