---
abstract: 'Perl interface to sck.to'
author:
  - 'celogeek <me@celogeek.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::More: 0.94
  WWW::Shorten: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300036, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Shorten-SCK
requires:
  Carp: 0
  Exporter: 0
  URI::Escape: 0
  WWW::Shorten::generic: 0
  parent: 0
  perl: 5.006
  strict: 0
  vars: 0
  warnings: 0
resources:
  bugtracker: https://tasks.celogeek.com/projects/perl-modules-www-shorten-sck
  homepage: https://tasks.celogeek.com/projects/perl-modules-www-shorten-sck
  repository: https://github.com/celogeek/perl-jedi.git
version: 0.4
x_Dist_Zilla:
  perl:
    version: 5.018001
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@GRS/@Filter/GatherDir'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@GRS/@Filter/PruneCruft'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@GRS/@Filter/ManifestSkip'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@GRS/@Filter/MetaYAML'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::License
      name: '@GRS/@Filter/License'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@GRS/@Filter/Readme'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@GRS/@Filter/ExtraTests'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@GRS/@Filter/ExecDir'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@GRS/@Filter/ShareDir'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@GRS/@Filter/Manifest'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@GRS/@Filter/TestRelease'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@GRS/@Filter/ConfirmRelease'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@GRS/ModuleBuild'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::ReportVersions
      name: '@GRS/ReportVersions'
      version: 1.110730
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: '@GRS/OurPkgVersion'
      version: 0.004000
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@GRS/Prepender'
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@GRS/AutoPrereqs'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: '@GRS/Prereqs'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@GRS/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@GRS/Test::Compile'
      version: 2.021
    -
      class: Dist::Zilla::Plugin::Test::UnusedVars
      name: '@GRS/Test::UnusedVars'
      version: 2.000005
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@GRS/PodCoverageTests'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@GRS/PruneFiles'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::ReadmeMarkdownFromPod
      name: '@GRS/ReadmeMarkdownFromPod'
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@GRS/MetaJSON'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::MetaResourcesFromGit
      name: '@GRS/MetaResourcesFromGit'
      version: 1.103620
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@GRS/MetaConfig'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@GRS/PodWeaver'
      version: 3.101642
    -
      class: Dist::Zilla::Plugin::PerlTidy
      name: '@GRS/PerlTidy'
      version: 0.13
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: '@GRS/Test::Perl::Critic'
      version: 2.112410
    -
      class: Dist::Zilla::Plugin::MetaResourcesFromGit
      name: MetaResourcesFromGit
      version: 1.103620
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300036
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300036
